env:
  es2021: true
  node: true
extends:
  - standard-with-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  no-console: 'off'
  import/extensions: 'off'
  '@typescript-eslint/no-misused-promises':
    - error
    - checksVoidReturn: false